# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

#theme: jekyll-theme-minimal
theme: samljen
title: 晓晓星空的主页
description: Bookmark this to keep an eye on my project updates!
logo: "logo.png"


